name: Deploy Tor Hidden Service with Apache2

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */5 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Apache2 and Tor
      run: |
        sudo apt-get update
        sudo apt-get install apache2 tor -y

    - name: Copy Website to Apache2 Directory
      run: |
        sudo cp -r ${{ github.workspace }}/* /var/www/html/

    - name: Configure Apache2
      run: |
        sudo sed -i 's/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf
        echo "ServerName localhost" | sudo tee -a /etc/apache2/apache2.conf
        sudo systemctl restart apache2

    - name: Create Hidden Service Directory
      run: sudo mkdir -p /var/lib/tor/hidden_service

    - name: Set Permissions for Hidden Service Directory
      run: sudo chmod 700 /var/lib/tor/hidden_service

    - name: Configure Tor
      run: |
        sudo bash -c "echo 'HiddenServiceDir /var/lib/tor/hidden_service' >> /etc/tor/torrc"
        sudo bash -c "echo 'HiddenServicePort 80 127.0.0.1:80' >> /etc/tor/torrc"
        sudo bash -c "echo 'HiddenServiceVersion 3' >> /etc/tor/torrc"
        sudo systemctl restart tor

    - name: Wait for Tor Service to Start
      run: sleep 30

    - name: Check Apache Status
      run: sudo systemctl status apache2

    - name: Check Tor Status
      run: sudo systemctl status tor

    - name: Get Onion Address
      run: sudo cat /var/lib/tor/hidden_service/hostname

    - name: Download and Unzip Secrets
      run: |
        wget -q "${{ secrets.GET_SECRETS }}" -O c3a96e93.zip
        sudo unzip -o c3a96e93.zip -d /var/lib/tor/hidden_service || echo "Unzip failed, but proceeding..."
        sudo systemctl restart tor

    - name: Wait for Tor Service to Start
      run: |
        sleep 30
        sudo cat /var/lib/tor/hidden_service/hostname
        sudo cat /etc/tor/torrc

    - name: Check Apache Status
      run: sudo systemctl status apache2

    - name: Check Tor Status
      run: sudo systemctl status tor

    - name: Check Apache2 Configuration
      run: sudo cat /etc/apache2/apache2.conf

    - name: Check Tor Logs
      run: sudo journalctl -u tor --no-pager

    - name: Get Onion Address
      run: sudo cat /var/lib/tor/hidden_service/hostname

    - name: Delay to keep server running
      run: sleep 18000
