name: Deploy Tor Hidden Service

on:
  push:
    branches:
      - main # or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest # or your preferred runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Tor
      run: |
        sudo apt-get update
        sudo apt-get install tor -y

    - name: Create Tor Directory
      run: mkdir tor
    
    - name: Enter Tor Directory
      run: cd tor
    
    - name: Clone GitHub Repository
      run: git clone https://github.com/anuragmuxui/anuragmuxui.github.io.git

    - name: Start Python Server
      run: |
          cd anuragmuxui.github.io
          nohup python3 -m http.server --bind 127.0.0.1 8080 &
          sleep 5 # Allow server to start
    
    - name: Configure Tor
      run: |
        sudo sed -i 's/#HiddenServiceDir \/var\/lib\/tor\/hidden_service\//HiddenServiceDir \/var\/lib\/tor\/hidden_service\//' /etc/tor/torrc
        sudo sed -i 's/#HiddenServicePort 80 127.0.0.1:80/HiddenServicePort 8080 127.0.0.1:8080/' /etc/tor/torrc
        sudo systemctl restart tor
    - name: Check if Python server running
      run: netstat -tuln | grep 8080
    
    - name: Wait for Tor Service to Start
      run: sleep 60  # Wait for 60 seconds to make sure service is up

    - name: Get Onion Address
      run: |
          sudo cat /var/lib/tor/hidden_service/hostname
          
    - name: Delay to keep server running
      run: |
        sleep 3600 # keep the server running for 1 hour, you can adjust as necessary
