name: Deploy GitHub Pages from Git to Tor Onion Service

on:
  push:
    branches:
      - main  # Or your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Ansible and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible git apt-transport-https curl gnupg2
          sudo apt-get install -y tor

      - name: Clone the Ansible Playbook Repository
        run: |
          git clone https://github.com/freddiebarrsmith/Ansible-Hidden-Service-Deployment.git
          cd Ansible-Hidden-Service-Deployment

      - name: Ensure Ansible Hosts File Exists
        run: |
          sudo mkdir -p /etc/ansible
          echo "localhost ansible_connection=local" | sudo tee /etc/ansible/hosts

      - name: Run Ansible Playbook for Tor Hidden Service
        run: |
          cd Ansible-Hidden-Service-Deployment
          ansible-playbook darkweb.yml

      - name: Serve Website
        run: |
          cd /home/tordir
          python3 -m http.server 80 &

      - name: Display Onion Address
        run: |
          cat /home/tordir/hostname
