name: Deploy GitHub Pages to Tor

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy-to-tor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download GitHub Pages Content
      run: |
        # Clone the GitHub Pages content
        git clone --depth 1 https://github.com/anuragmuxui/anuragmuxui.github.io.git site-content
        ls site-content

    - name: Deploy to Tor
      run: |
        # Install Docker
        sudo apt-get update
        sudo apt-get install -y docker.io

        # Create a Docker network
        docker network create tor_network

        # Run a Tor container to generate a hidden service
        docker run -d \
          --name tor \
          --network tor_network \
          -v $(pwd)/hidden_service:/var/lib/tor/hidden_service \
          dperson/torproxy \
          -f "HiddenServiceDir /var/lib/tor/hidden_service\nHiddenServicePort 80 127.0.0.1:8080"

        # Serve GitHub Pages content using an Nginx container
        docker run -d \
          --name static_server \
          --network tor_network \
          -v $(pwd)/site-content:/usr/share/nginx/html:ro \
          -p 8080:80 \
          nginx:alpine

        # Wait for the .onion address to be generated
        sleep 10

        # Display the .onion address
        cat hidden_service/hostname

    - name: Save .onion Address
      uses: actions/upload-artifact@v3
      with:
        name: onion-address
        path: hidden_service/hostname
